[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = {version = "0.32.2", features =["rand"]}
autodiff = "0.6.0"
convolutions-rs = "0.3.4"
plotters = "0.3.5"